apiVersion: v2
name: linkops-app
description: A Helm chart for the LinkOps application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - mlops
  - ai
  - microservice
home: https://github.com/jimjrxieb/LinkOps-MLOps
sources:
  - https://github.com/jimjrxieb/LinkOps-MLOps
maintainers:
  - name: LinkOps Team
    email: team@linkops.com 