AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Bucket for Portfolio Application artifacts and backups

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - development
      - staging
      - production
    Description: Environment name

  RetentionDays:
    Type: Number
    Default: 90
    Description: Days to retain non-current versions before deletion

Resources:
  # Artifacts Bucket
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub 'portfolio-artifacts-${AWS::AccountId}-${Environment}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: !Ref RetentionDays
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
          - Id: DeleteIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      Tags:
        - Key: Application
          Value: portfolio
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: artifacts

  # Bucket Policy
  ArtifactsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # Deny non-HTTPS access
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !GetAtt ArtifactsBucket.Arn
              - !Sub '${ArtifactsBucket.Arn}/*'
            Condition:
              Bool:
                aws:SecureTransport: 'false'

  # IAM Policy for S3 Access
  S3AccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub 'portfolio-${Environment}-s3-access'
      Description: Policy to access Portfolio S3 bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource:
              - !GetAtt ArtifactsBucket.Arn
              - !Sub '${ArtifactsBucket.Arn}/*'

Outputs:
  ArtifactsBucketName:
    Description: S3 Bucket Name
    Value: !Ref ArtifactsBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'

  ArtifactsBucketArn:
    Description: S3 Bucket ARN
    Value: !GetAtt ArtifactsBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BucketArn'

  S3AccessPolicyArn:
    Description: S3 Access Policy ARN
    Value: !Ref S3AccessPolicy
    Export:
      Name: !Sub '${AWS::StackName}-S3AccessPolicyArn'
