AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Secrets Manager secrets for Portfolio Application

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - development
      - staging
      - production
    Description: Environment name

  RotationDays:
    Type: Number
    Default: 90
    Description: Number of days between automatic secret rotation

Resources:
  # Claude API Key Secret
  ClaudeAPIKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'portfolio/${Environment}/claude-api-key'
      Description: Claude API key for Portfolio application
      Tags:
        - Key: Application
          Value: portfolio
        - Key: Environment
          Value: !Ref Environment
      # Note: Actual secret value should be set manually or via CLI
      # aws secretsmanager put-secret-value --secret-id portfolio/production/claude-api-key --secret-string "your-api-key"

  # OpenAI API Key Secret (optional, for fallback)
  OpenAIAPIKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'portfolio/${Environment}/openai-api-key'
      Description: OpenAI API key for Portfolio application (fallback)
      Tags:
        - Key: Application
          Value: portfolio
        - Key: Environment
          Value: !Ref Environment

  # Database Credentials Secret
  DatabaseCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'portfolio/${Environment}/database-credentials'
      Description: Database credentials for Portfolio application
      GenerateSecretString:
        SecretStringTemplate: '{"username": "portfolio_user"}'
        GenerateStringKey: password
        PasswordLength: 32
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Application
          Value: portfolio
        - Key: Environment
          Value: !Ref Environment

  # ChromaDB Authentication Secret
  ChromaDBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'portfolio/${Environment}/chromadb-auth'
      Description: ChromaDB authentication token
      GenerateSecretString:
        PasswordLength: 64
        ExcludePunctuation: true
      Tags:
        - Key: Application
          Value: portfolio
        - Key: Environment
          Value: !Ref Environment

  # IAM Policy for Secrets Access
  SecretsAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub 'portfolio-${Environment}-secrets-access'
      Description: Policy to access Portfolio secrets
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource:
              - !Ref ClaudeAPIKeySecret
              - !Ref OpenAIAPIKeySecret
              - !Ref DatabaseCredentialsSecret
              - !Ref ChromaDBSecret
          - Effect: Allow
            Action:
              - kms:Decrypt
            Resource: '*'
            Condition:
              StringEquals:
                kms:ViaService: !Sub 'secretsmanager.${AWS::Region}.amazonaws.com'

Outputs:
  ClaudeAPIKeySecretArn:
    Description: Claude API Key Secret ARN
    Value: !Ref ClaudeAPIKeySecret
    Export:
      Name: !Sub '${AWS::StackName}-ClaudeSecretArn'

  OpenAIAPIKeySecretArn:
    Description: OpenAI API Key Secret ARN
    Value: !Ref OpenAIAPIKeySecret
    Export:
      Name: !Sub '${AWS::StackName}-OpenAISecretArn'

  DatabaseCredentialsSecretArn:
    Description: Database Credentials Secret ARN
    Value: !Ref DatabaseCredentialsSecret
    Export:
      Name: !Sub '${AWS::StackName}-DatabaseSecretArn'

  ChromaDBSecretArn:
    Description: ChromaDB Auth Secret ARN
    Value: !Ref ChromaDBSecret
    Export:
      Name: !Sub '${AWS::StackName}-ChromaDBSecretArn'

  SecretsAccessPolicyArn:
    Description: Secrets Access Policy ARN
    Value: !Ref SecretsAccessPolicy
    Export:
      Name: !Sub '${AWS::StackName}-SecretsAccessPolicyArn'
