# JSA-DevSec YAML Linter Configuration
# Strict YAML validation for Kubernetes manifests and Helm charts
# https://yamllint.readthedocs.io/

extends: default

rules:
  # Line length (allow longer for K8s manifests)
  line-length:
    max: 200
    allow-non-breakable-inline-mappings: true

  # Indentation (2 spaces for YAML)
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Comments
  comments:
    require-starting-space: true
    min-spaces-from-content: 1

  # Braces and brackets
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0

  # Colons and commas
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  commas:
    max-spaces-before: 0
    min-spaces-after: 1

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

  # Document markers
  document-start: disable
  document-end: disable

  # Keys
  key-duplicates: enable
  key-ordering: disable

  # Truthy values
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false

  # New line at end of file
  new-line-at-end-of-file: enable

  # Trailing spaces
  trailing-spaces: enable

  # Hyphens
  hyphens:
    max-spaces-after: 1

  # Octal values (K8s often uses these for permissions)
  octal-values: disable

  # Anchors
  anchors:
    forbid-undeclared-aliases: true
    forbid-duplicated-anchors: true

ignore: |
  .git/
  .github/
  node_modules/
  vendor/
  charts/*/charts/
  **/templates/**
