apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: linkops
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  # echo -n "your_secure_password" | base64
  password: "cG9zdGdyZXM="  # postgres (base64 encoded)
  username: "cG9zdGdyZXM="  # postgres (base64 encoded)
  database: "bGlua29wcw=="  # linkops (base64 encoded) 