apiVersion: apps/v1
kind: Deployment
metadata:
  name: whis
  namespace: linkops
  labels:
    app: whis
    component: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whis
  template:
    metadata:
      labels:
        app: whis
        component: microservice
    spec:
      containers:
      - name: whis
        image: linkopsacr.azurecr.io/whis:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: linkops-secrets
              key: database-url
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        - name: SANITIZER_URL
          value: "http://sanitizer:8000"
        - name: FICKNURY_URL
          value: "http://ficknury:8000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: acr-secret 