apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: linkops
  labels:
    app: linkops-backend
    app.kubernetes.io/name: linkops-backend
    app.kubernetes.io/part-of: linkops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: linkops-backend
  template:
    metadata:
      labels:
        app: linkops-backend
    spec:
      serviceAccountName: linkops-backend-sa
      containers:
      - name: backend
        image: ACR_NAME.azurecr.io/linkops-backend:IMAGE_TAG
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: linkops-secrets
              key: DATABASE_URL
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: linkops-secrets
              key: OPENAI_API_KEY
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: linkops-secrets
              key: SECRET_KEY
        - name: AZURE_APPINSIGHTS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: linkops-secrets
              key: AZURE_APPINSIGHTS_CONNECTION_STRING
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linkops-backend-sa
  namespace: linkops
  annotations:
    azure.workload.identity/client-id: "${AZURE_CLIENT_ID}"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: linkops
  labels:
    app: linkops-backend
    app.kubernetes.io/name: linkops-backend
    app.kubernetes.io/part-of: linkops
spec:
  selector:
    app: linkops-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP 