apiVersion: v1
kind: Service
metadata:
  name: katie
  namespace: linkops
  labels:
    app: katie
    component: microservice
spec:
  selector:
    app: katie
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP 