apiVersion: v1
kind: Service
metadata:
  name: james
  namespace: linkops
  labels:
    app: james
    component: microservice
spec:
  selector:
    app: james
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP 