apiVersion: v1
kind: Service
metadata:
  name: igris
  namespace: linkops
  labels:
    app: igris
    component: microservice
spec:
  selector:
    app: igris
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP 