# ArgoCD Application for OPA Gatekeeper Policies
# Deploy order: ConstraintTemplates first (wave 0), then Constraints (wave 1)
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-gatekeeper-templates
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jimjrxieb/LinkOps-Manifests.git
    targetRevision: HEAD
    path: policies/gatekeeper
    directory:
      include: "constraint-templates.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-gatekeeper-constraints
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jimjrxieb/LinkOps-Manifests.git
    targetRevision: HEAD
    path: policies/gatekeeper
    directory:
      include: "constraints.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
