apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: monitoring
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  # To encode: echo -n "your_secure_password" | base64
  admin-password: "REPLACE_WITH_BASE64_ENCODED_ADMIN_PASSWORD" 