apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkops
resources:
  - namespace.yaml
  - secrets.yaml
  - grafana-secret.yaml
  - ingress.yaml
  - postgres/
  - james/
  - whis/
  - katie/
  - igris/
  - frontend/

commonLabels:
  app: linkops
  project: linkops
  managed-by: kustomize 