apiVersion: v1
kind: Secret
metadata:
  name: linkops-secrets
  namespace: linkops
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  # To encode: echo -n "your_value" | base64
  database-url: "REPLACE_WITH_BASE64_ENCODED_DATABASE_URL"
  openai-api-key: "REPLACE_WITH_BASE64_ENCODED_OPENAI_API_KEY"
  acr-username: "REPLACE_WITH_BASE64_ENCODED_ACR_USERNAME"
  acr-password: "REPLACE_WITH_BASE64_ENCODED_ACR_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: linkops
type: kubernetes.io/dockerconfigjson
data:
  # To generate this secret:
  # kubectl create secret docker-registry acr-secret \
  #   --docker-server=your-registry.azurecr.io \
  #   --docker-username=your-username \
  #   --docker-password=your-password \
  #   --docker-email=your-email@example.com \
  #   --namespace=linkops
  .dockerconfigjson: "REPLACE_WITH_BASE64_ENCODED_DOCKER_CONFIG_JSON" 